### ISSUE TITLE
Parameter Definition

### ISSUE THREAD

**Issue by angelespinozae** [paulofelipe/cp2015-jax#1]
Hello Paulo!

Thank you very much for sharing this code. I'm trying to update the results of the model, and it has been super useful. I have one quick question.

Could you please help me clarify what the parameter wL_n is (this is a vector of 31x1)? I couldn't determine this myself after reading your code, Caliendo and Parro's paper, and the README.

I suspect this is the total expenditure in final goods, but I'm not entirely sure. Could you please tell me how you computed it from the original data?

Thank you very much!

**Comment by paulofelipe** [comment]
Hi Angel,

wL_n is the initial total value added by each region.

Best,

Paulo
